### ISSUE TITLE
Multiple issues...

### ISSUE THREAD

**Issue by tblancher** [ezh/android-component-DigiSSHD#1]
The UI is overly complicated.  While the component gives you the option to change the port to something other than 2222, the service will not load unless the port is 2222.  Also, the service warns against setting the port to 22, for what reason I dunno.  The server does not seem to allow root users to connect, which makes this client useless to me for my purposes.  During my testing, I stopped being able to connect, it kept rejecting the password that I set in the interface for the 'android' user.

I have uninstalled this crappy server.  I am not willing to reinstall it and perform more testing.

**Comment by ezh** [comment]
It is an alfa stage (version 0.1.05), and I wrote about it in software description.
Market statistics and user feedback give me assurance that Digi SSHD useful already, but not for everyone.
I hope that your experience with DigiSSHD is not a critical mistake and the greatest disappointment in all of human history.

It is so sad that this software is useless for you.
I am sure, you will give it second chance when it will be 1.0 ;-) Anyway, thank you for your efforts.

BTW if you really want help next time please provide some sketches of user interface or cooperate with developer ;-) for bug elimination.

Thank you for opinion. I will try to simplify UI and find what's wrong with su login.
I close this issue, because fuse investigation unresonable without any concrete details.

PS I published new version 0.2 that contain a lot of fixes, but there are still some problems.

Anyway, thank you for efforts.

King regards,
Alexey
